{% set data = load_setup_py_data() %}

package:
  name: scared
  version: {{ data['version'] }}

source:
  path: ../../

build:
  
  

requirements:
  build:
    - setuptools
    - wheel
  host:
    - python {{ python }}
    - setuptools>=40.0
    - wheel
    - pip
    - psutil
    - numpy {{ numpy_version }} 
  run:
    - python
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - scared
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - pycryptodome
  commands:
    - pytest

about:
  home: https://www.eshard.com/
  license: PROPRIETARY
  summary: 'scared Python library'
