{% set version = "0.8.12" %}

package:
  name: scared
  version: {{ version }}

source:
  path: ../

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - setuptools>=40.0
    - wheel
    - pip
    - numpy
    - cython
  run:
    - python {{python}}
    - numpy
    - estraces
    - psutil
    - numba
    - scipy
    - cython
about:
  home: https://gitlab.com/eshard/scared
  license: GNU LGPL V3
  license_file: LICENSE
  summary: scared is a side-channel analysis framework.
