{% set version = "0.9.1" %}

package:
  name: scared
  version: {{ version }}

source:
  path: ../

build:
  number: 1

requirements:
  host:
    - python {{ python }}
    - setuptools>=40.0
    - wheel
    - pip
    - numpy
  run:
    - python
    - numpy
    - estraces
    - psutil
    - numba
    - scipy
about:
  home: https://gitlab.com/eshard/scared
  license: GNU LGPL V3
  license_file: LICENSE
  summary: scared is a side-channel analysis framework.
