{% set data = load_setup_py_data() %}

package:
  name: scared-dev
  version: {{ data['version'] }}

source:
  path: ../../

requirements:
  host:
    - python {{ python }}
    - setuptools>=40.0
    - wheel
    - pip
    - numpy>=1.20.3
  run:
    - python
    {% for dep in data['install_requires'] %}
      {% if dep.lower() == 'estraces' %}
    - estraces-dev
      {% else %}
    - {{ dep.lower() }}
      {% endif %}
    {% endfor %}

tests:
  import:
    - scared
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - py.test
about:
  home: https://gitlab.com/eshard/scared
  license: GNU LGPL V3
  license_file: LICENSE
  summary: scared is a side-channel analysis framework.
